In [9]:
import pandas as pd
import numpy as np
st1 = pd.Series({"국어" : 100, "영어" : 80,"수학" : 90})
st2 = pd.Series({"국어" : 90, "영어" : 80,"수학" : 80})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1/st2),2)
print(add)
print(sub)
print(mul)
print(div)

국어    190
영어    160
수학    170
dtype: int64
국어    10
영어     0
수학    10
dtype: int64
국어    9000
영어    6400
수학    7200
dtype: int64
국어    1.11
영어    1.00
수학    1.12
dtype: float64


In [6]:
df = pd.concat([add,sub,mul,div], axis = 1)
df

0   1     2     3
국어  190  10  9000  1.11
영어  160   0  6400  1.00
수학  170  10  7200  1.12

In [7]:
pd.DataFrame([add,sub,mul,div],index=["덧셈","뺄셈","곱셈","나눗셈"])

국어      영어       수학
덧셈    190.00   160.0   170.00
뺄셈     10.00     0.0    10.00
곱셈   9000.00  6400.0  7200.00
나눗셈     1.11     1.0     1.12

In [11]:
st1 = pd.Series({"국어" : np.nan, "영어" : 80,"수학" : 90})
st2 = pd.Series({"국어" : 90,"수학" : 80})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1/st2),2)

pd.DataFrame([add,sub,mul,div],index=["덧셈","뺄셈","곱셈","나눗셈"])

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [12]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4),columns = list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape(4,5),columns = list("abcde"))


df2.loc[1,"b"] = np.nan
print(df1)
print(df2)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [20]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [26]:
add_dat = df1.add(df2,fill_value=0)
sub_dat = df1.sub(df2,fill_value=0)
mul_dat = df1.mul(df2,fill_value=0)
div_dat = round(df1.div(df2,fill_value=0),2)


div_dat

a     b     c     d    e
0  NaN  1.00  1.00  1.00  0.0
1  0.8   inf  0.86  0.88  0.0
2  0.8  0.82  0.83  0.85  0.0
3  0.0  0.00  0.00  0.00  0.0

In [28]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [55]:
df  = pd.DataFrame(np.random.randn(4,3),columns = list("bde"),
                  index = ["서울","부산","인천","대구"])
df

b         d         e
서울 -1.017656 -1.438228  0.265267
부산 -0.447438 -1.093220  0.306456
인천 -2.320785 -0.657659 -0.771220
대구 -0.815303  0.251019 -0.768072

In [35]:
sr = df.iloc[0]
sr

b   -0.294868
d    0.296142
e    0.276800
Name: 서울, dtype: float64

In [36]:
df - sr

b         d         e
서울  0.000000  0.000000  0.000000
부산  1.235463 -0.005411  1.079260
인천  1.234533 -1.123006 -0.332004
대구 -0.410069 -0.694345  1.828511

In [37]:
np.abs(df)

b         d         e
서울  0.294868  0.296142  0.276800
부산  0.940595  0.290731  1.356061
인천  0.939665  0.826864  0.055203
대구  0.704937  0.398204  2.105312

커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map함수 : DataFrame 타입이 아니라, 반드시 Series 타입에서만 사용
- apply함수 : 커스텀 함수를 사용하기 위해 DataFrame에서 복수 개의 컬럼이 필요하다면, apply함수를 사용
- applymap함수 : DataFrame클래스의 함수이긴 하나, 위의 apply함수처럼 각 row(axis=1)나 각 column(axis=0)별로 
작동하는 함수가 아니라, 각 요소(element)별로 작동  
마치 선형대수에서 벡터에 스칼라를 연산하면, 벡터의 요소 하나하나에 해당 연산을 해주는 것처럼(elementwise) 
적용하는 DataFrame의 각 요소마다 커스텀 함수(반드시 Single vaule를 반환하는)를 수행한다고 보면 된다. 
applymap에 인자로 전달하는 커스텀함수가 Single value로부터 Single value를 반환한다는 점이 중요하다

In [39]:
f = lambda x: x.max() - x.min()

df.apply(f)

b    1.645532
d    1.123006
e    2.160515
dtype: float64

In [40]:
df.apply(f,axis = 1)

서울    0.591010
부산    1.065330
인천    1.766529
대구    2.810249
dtype: float64

In [44]:
f = lambda x: x.sum() / x.count()

a = np.abs(df).apply(f, axis = 1)
a

서울    0.289270
부산    0.862462
인천    0.607244
대구    1.069484
dtype: float64

In [54]:
df.insert(3,"평균",a)
df

b         d         e        평균
서울  0.483970  0.049292  0.171205  0.289270
부산  0.231238  0.164180 -0.525658  0.862462
인천 -1.315358 -0.634674  0.377216  0.607244
대구 -1.419679 -0.561371 -1.955505  1.069484

In [56]:
def f(x):
    return pd.Series([x.min(),x.max()], index = ["min","max"])

In [59]:
df.apply(f, axis = 1)

min       max
서울 -1.438228  0.265267
부산 -1.093220  0.306456
인천 -2.320785 -0.657659
대구 -0.815303  0.251019

In [62]:
f = lambda x: "%.2f" %x
df.applymap(f)

b      d      e
서울  -1.02  -1.44   0.27
부산  -0.45  -1.09   0.31
인천  -2.32  -0.66  -0.77
대구  -0.82   0.25  -0.77

In [63]:
df['e'].map(f)

서울     0.27
부산     0.31
인천    -0.77
대구    -0.77
Name: e, dtype: object