In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### 과제1_0420
앞에 언급한 사항들의 사례를 작성해서 의미를 확인하고 설명하시오

In [2]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2],[2,3],[3,4]])
z = np.array([[1,1],[2,2],[3,3]])


print(x)
print(y)
print(x@y)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [2 3]
 [3 4]]
[[14 20]
 [32 47]]


In [3]:
print(x.T)
print(y)
print(x.T@y)

[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [2 3]
 [3 4]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [4]:
print(x@y)
print(y@x)

[[14 20]
 [32 47]]
[[ 9 12 15]
 [14 19 24]
 [19 26 33]]


In [5]:
print(x@(y+z))
print(x@y + x@z)

[[28 34]
 [64 79]]
[[28 34]
 [64 79]]


In [6]:
print((z+y).T)
print(z.T + y.T)

[[2 4 6]
 [3 5 7]]
[[2 4 6]
 [3 5 7]]


In [7]:
print((x@y).T)
print(y.T@x.T)

[[14 32]
 [20 47]]
[[14 32]
 [20 47]]


#### 과제2_0420
배열 e의 행렬식을 구하면 에러가 발생됩니다. 행렬식의 의미를 감안하여 e행렬을 수정하여 행렬식을 계산하시오.
- 행렬식을 계산하시오.
- 역행렬을 구하시오.
- 역행렬이 맞는지 검증하시오.

In [8]:
e = np.array([[1,0,0],[0,1,0]])

e = np.array([[1,0,0],[0,0,1],[0,1,0]])
print(e)
print(np.linalg.det(e))
a = np.linalg.inv(e)
print(a)
print(e@a)

[[1 0 0]
 [0 0 1]
 [0 1 0]]
-1.0
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 과제3_0420
아래 두 행렬을 생성해서 각각 a1, b1으로 저장하고 행렬 내적을 계산한 결과를 출력하시오.

[[1,2,3],[4,5,6]]

[[10,11],[12,13],[14,15]]

In [9]:
a1 = np.array([[1,2,3],[4,5,6]])
b1 = np.array([[10,11],[12,13],[14,15]])

a1@b1

array([[ 76,  82],
       [184, 199]])