#### NumPy는 “Numerical Python“의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공
* Numerical Python을 의미하는 NumPy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
* 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
* 넘파이의 기본 데이터 타입은 ndarray. ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

NumPy 특징

- 강력한 N 차원 배열 객체
- 정교한 브로드케스팅(Broadcast) 기능
- C/C ++ 및 포트란 코드 통합 도구
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환(Fourier transform, FT)은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

Numpy Documentation  

https://numpy.org/doc/1.21/index.html

Numpy는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되었다.
- Numpy는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장
- Numpy의 각종 알고리즘은 모두 C로 작성되어 타입 검사나 다른 오버헤드 없이 메모리를 직접 조작
- Numpy 배열은 또한 내장 파이썬의 연속된 자료형들보다 훨씬 더 적은 메모리를 사용
- Numpy 연산은 파이썬 반복문을 사용하지 않고 전체 배열에 대한 복잡한 계산을 수행

In [1]:
import numpy as np

z = np.arange(1000000)
zlist = list(range(1000000))

In [2]:
%time for _ in range(10) : z2 = zlist * 2
%time for _ in range(10) : z2 = z * 2

Wall time: 196 ms
Wall time: 22.9 ms


In [3]:
np.random.seed(0)
data = np.random.randn(2,3)
print(data,"\n")
print(data * 10, "\n")
print(data + data)

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]] 

[[17.64052346  4.00157208  9.78737984]
 [22.40893199 18.6755799  -9.7727788 ]] 

[[ 3.52810469  0.80031442  1.95747597]
 [ 4.4817864   3.73511598 -1.95455576]]


In [4]:
print(data.shape)
print(data.dtype)
print(data.ndim)

(2, 3)
float64
2


In [5]:
data1 = [6,7,5,8,0,1]
arr1 = np.array(data1)
print(arr1,type(arr1))

[6 7 5 8 0 1] <class 'numpy.ndarray'>


In [6]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2,type(arr2))
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
(2, 4)
2
int32


In [7]:
data3 = [[[1,2,3,4,5],[6,7,8,9,10]],
         [[1,2,3,4,5],[6,7,8,9,10]],
         [[1,2,3,4,5],[6,7,8,9,10]]]

arr3 = np.array(data3)
print(arr3,type(arr3))
print(arr3.shape)
print(arr3.ndim)
print(arr3.dtype)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] <class 'numpy.ndarray'>
(3, 2, 5)
3
int32


배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [8]:
print(np.zeros(10))
print(np.zeros((3,5)))
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [9]:
print(np.ones(10))
print(np.ones((3,5)))
print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [10]:
a = np.arange(10).reshape(2,5)

print(np.zeros_like(a))
print(np.ones_like(a))
print(np.full_like(a,5))

[[0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[5 5 5 5 5]
 [5 5 5 5 5]]


In [11]:
ar = np.arange(15)
print(ar)
ar2 = ar.reshape(3,5)
print(ar2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
array1 = np.arange(10)

array1 = array1.reshape(5,2)
print(array1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
ar = np.arange(20)
print(ar,"\n")

ar = ar.reshape(4,5)
print(ar,"\n")

ar = ar.reshape(2,2,5)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [14]:
ar1 = np.arange(30)
print("1 -> 2,3차원")
ar12 = ar1.reshape(6,-1)
print(ar12, "\n")
ar13 = ar1.reshape(-1,3,5)
print(ar13)

1 -> 2,3차원
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [15]:
print("2 -> 1,3차원")
print(ar12, "\n")
ar21 = ar12.reshape(-1,)
ar23 = ar12.reshape(-1,2,5)
print(ar21, "\n")
print(ar23)

2 -> 1,3차원
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [16]:
print("3 -> 1,2차원")
ar31 = ar13.reshape(-1,)
ar32 = ar13.reshape(-1,5)
print(ar31, "\n")
print(ar32)

3 -> 1,2차원
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [17]:
ar3 = np.arange(30).reshape(3,2,5)
print(ar3, type(ar3),"\n")
l3 = ar3.tolist()
print(l3, type(l3))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] <class 'numpy.ndarray'> 

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]] <class 'list'>


행렬의 종류

https://math-development-geometry.tistory.com/52

- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 삼각행렬은 주대각선 원소를 기준으로 위 또는 아래에 있는 성분이 모두 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬

In [18]:
# 정방행렬
a = np.full((2,2),7)
a

array([[7, 7],
       [7, 7]])

In [19]:
# 항등행렬 = 단위행렬
ar = np.eye(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 대각행렬
diag_mat = np.diag([1,2,3,4,5])
diag_mat

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [21]:
# 삼각행렬
upper_tri_mat = np.triu([[1,2,3],[4,5,6],[7,8,9]])
print(upper_tri_mat,"\n")
lower_tri_mat = np.tril([[1,2,3],[4,5,6],[7,8,9]])
print(lower_tri_mat)

[[1 2 3]
 [0 5 6]
 [0 0 9]] 

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [22]:
# 전치행렬
mat = np.array([[1,2],[3,4],[5,6]])
print(mat, "\n")
transpose_mat = mat.T
transpose_mat

[[1 2]
 [3 4]
 [5 6]] 



array([[1, 3, 5],
       [2, 4, 6]])

# 직교행렬 
- 행과 열이 서로 직교하는 정방행렬
- 모든 열벡터와 행벡터가 서로 직교하고 크기가 1인 단위벡터
- np.linalg.qu() 함수를 사용하여 QR분해를 수행하여 직교행렬을 추출
- q를 추출하여 직교행렬 orth_mat을 만든다.
- np.dot(orth_mat,orth_mat.T)를 계산하여 직교성을 검증
- np.allclose() 함수로 두 행렬이 동일한지 검사, True를 반환하면 두 행렬은 동일.

In [23]:

mat = np.random.randn(3,3)
print(mat)

# qr 분해
q,r = np.linalg.qr(mat)

# 직교행렬 추출
orth_mat = q
print(orth_mat)

# 직교성 검증
print(np.allclose(np.dot(orth_mat,orth_mat.T),np.eye(3)))

[[ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323]]
[[-0.73954478  0.64510245 -0.19213628]
 [-0.31960813 -0.58776037 -0.74322836]
 [-0.59238853 -0.48824233  0.6408551 ]]
True


In [24]:
ar2 = np.arange(1,10).reshape(3,3)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
print(ar2[2])
print(ar2[0][2])

[7 8 9]
3


In [26]:
a = np.arange(1,10).reshape(3,3)
a
print(a[:2,:2])
print(a[1:3,0:3])
print(a[0::1])
print(a[:2,0:2])
print(a[:2,0:1])

[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1]
 [4]]


In [27]:
ar = np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
ar[ar > 5]

array([6, 7, 8, 9])

In [59]:
# ar에서 아래아 같이 출력하시오
#[3,6]
#[[1.2],[4,5]]
#[[1,2,3],[4,5,6]]
ar = ar.reshape(3,3)
print(ar)
print(ar[0:2,2])
print(ar[:2,:2])
print(ar[:2,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [30]:
# 1~ 14까지 ndarray를 만들어 array_e로 저장하고 array_e/2 > 3을 만족하는 값을 불린 인덱스로 출력하세요.

array_e = np.arange(1,15)
array_e[(array_e/2)>5]

array([11, 12, 13, 14])

In [31]:
# arr에서 0.5보다 큰 수를 출력하라
arr = np.random.randn(100)
arr[arr > 0.5]

array([1.49407907, 0.6536186 , 0.8644362 , 2.26975462, 1.53277921,
       1.46935877, 1.23029068, 1.20237985, 1.9507754 , 0.77749036,
       0.72909056, 1.13940068, 0.90082649, 1.48825219, 1.89588918,
       1.17877957, 1.05445173, 1.22244507, 0.97663904, 0.70657317,
       1.78587049, 1.8831507 , 0.96939671, 1.94362119, 1.92294203,
       1.48051479, 1.86755896, 0.90604466, 1.91006495])

In [32]:
np.random.seed(0)
data = np.arange(30)
data[data%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [60]:
# [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
data = np.array([1,2,0,0,4,0])
np.nonzero(data)

(array([0, 1, 4], dtype=int64),)

In [34]:
bools = np.array([False,False,True,True])
bools

array([False, False,  True,  True])

In [35]:
# 하나 이상의 값이 True인지 검사
bools.any()

True

In [36]:
# 모든 원소가 True인지 검사
bools.all()

False

In [37]:
# arr에서 0보다 크면 2, 아니면 -2로 변경하라
arr = np.random.randn(4,4)
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2,  2],
       [ 2, -2,  2, -2],
       [-2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [38]:
# arr의 모든 양수를 2로 바꾸세요.
arr = np.random.randn(4,4)
arr[arr > 0] = 2
arr

array([[ 2.        , -0.20515826,  2.        , -0.85409574],
       [-2.55298982,  2.        ,  2.        , -0.74216502],
       [ 2.        , -1.45436567,  2.        , -0.18718385],
       [ 2.        ,  2.        ,  2.        ,  2.        ]])

In [39]:
# np.sort() : 복사본을 정렬 반환
np.random.seed(0)
arr = np.random.randint(1,100,size = 10)
arr

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [40]:
np.sort(arr)

array([10, 22, 37, 45, 48, 65, 68, 68, 84, 88])

In [41]:
ar2 = np.array([[8,12],
              [7,1]])
np.sort(ar2, axis = 0)

array([[ 7,  1],
       [ 8, 12]])

In [42]:
# ndarray.sort() : 원본에 정렬 적용

arr = np.random.randint(10,size = 10)
arr.sort()
arr

array([1, 1, 5, 6, 6, 7, 7, 8, 8, 8])

In [43]:
arr = np.random.randint(10,size = (10,10))
arr

array([[9, 8, 9, 4, 3, 0, 3, 5, 0, 2],
       [3, 8, 1, 3, 3, 3, 7, 0, 1, 9],
       [9, 0, 4, 7, 3, 2, 7, 2, 0, 0],
       [4, 5, 5, 6, 8, 4, 1, 4, 9, 8],
       [1, 1, 7, 9, 9, 3, 6, 7, 2, 0],
       [3, 5, 9, 4, 4, 6, 4, 4, 3, 4],
       [4, 8, 4, 3, 7, 5, 5, 0, 1, 5],
       [9, 3, 0, 5, 0, 1, 2, 4, 2, 0],
       [3, 2, 0, 7, 5, 9, 0, 2, 7, 2],
       [9, 2, 3, 3, 2, 3, 4, 1, 2, 9]])

In [44]:
arr.sort(axis = 1)
arr.sort(axis = 0)
arr

array([[0, 0, 0, 1, 2, 2, 3, 4, 5, 8],
       [0, 0, 0, 2, 2, 3, 3, 4, 6, 9],
       [0, 0, 1, 2, 2, 3, 3, 5, 7, 9],
       [0, 0, 1, 2, 3, 3, 4, 5, 7, 9],
       [0, 1, 2, 2, 3, 3, 4, 7, 7, 9],
       [0, 1, 2, 3, 3, 4, 5, 7, 8, 9],
       [0, 1, 2, 3, 3, 4, 5, 7, 8, 9],
       [1, 2, 3, 4, 4, 5, 5, 7, 9, 9],
       [1, 3, 4, 4, 4, 5, 6, 8, 9, 9],
       [3, 4, 4, 4, 5, 6, 7, 8, 9, 9]])

In [45]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 떄
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
sort_indices

[3 1 9 5]


array([1, 0, 3, 2], dtype=int64)

In [46]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식, npy 파일로 저장
arr = np.arange(10)
np.save("some_array", arr)

np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# np.savez : 여러 개의 배열을 압축된 형식으로 저장
np.savez("array_archive.npz", a = arr, b = arr)
arch = np.load("array_archive.npz")
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# 인덱싱을 사용하여 [1,0,1,0,1,0,1,0,1,0]을 출력하세요.
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[:] = arr%2
arr

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [61]:
# 1 ~ 100을 아래와 같이 출력하세요
arr = np.arange(1,101).reshape(10,10)
arr[1::2] = arr[1::2, ::-1]
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

In [50]:
# np.ones((10,10))을 아래와 같이 출력하세요
arr = np.ones((10,10))
arr[1:9,1:9] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
#  np.ones((5,5))을 아래와 같이 출력하세요
arr = np.zeros((10,10))
arr[2:8,2:8] = 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
# np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
arr = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2 != 0:
            arr[i][j] = 1
print(arr)
arr = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [53]:
arr = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [54]:
# np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요
arr = np.arange(336).reshape(6,7,8)
np.unravel_index(100, arr.shape)

(1, 5, 4)